<?php

namespace PHPOnCouch;

use InvalidArgumentException,
    PHPOnCouch\Exceptions,
    PHPUnit_Framework_TestCase,
    stdClass;

require_once join(DIRECTORY_SEPARATOR, [__DIR__, '_config', 'config.php']);

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-11-01 at 01:49:47.
 */
class CouchTest extends PHPUnit_Framework_TestCase {

    private $host = 'localhost';
    private $port = '5984';

    /**
     *
     * @var PHPOnCouch\Couch
     */
    private $couch;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $config = \config::getInstance();
        $this->aUrl = $config->getUrl($this->host, $this->port, $config->getFirstAdmin());
        $this->couch_server = 'http://' . $this->host . ':' . $this->port . '/';

        $this->couch = new Couch($this->aUrl);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->couch = null;
    }
    
    public function testSessionAccessors(){
        $session = "Y291Y2g6NENGNDgzNz ";
        $this->couch->setSessionCookie($session);
        $this->assertEquals($session,$this->couch->getSessionCookie());
    }

}
