# GitHub Action for CodeIgniter
name: Testing PHPOnCouch
on: [ push, pull_request ]

env:
  HTTP_ADAPTER: curl
  DSN: "http://admin:password@127.0.0.1:5984"

jobs:
  build:
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '5.6', '7.2' ]
        couchdb-version: [ '3.1' ]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, curl, dom
          coverage: xdebug
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      - run: 'export DISPLAY=:99.0'

      # CouchDB Setup
      - name: Set up CouchDB
        uses: iamssen/couchdb-github-action@master
        with:
          couchdb-version: ${{ matrix.couchdb-version }}
      - name: Create missing tables
        run: curl -X PUT $DSN/_users  && curl -X PUT $DSN/_replicator
      - name: Add non-admin CouchDB user
        run: |
          curl -X PUT $DSN/_users/org.couchdb.user:client \
               -H "Accept: application/json" \
               -H "Content-Type: application/json" \
               -d '{"name": "client", "password": "client", "roles": [], "type": "user"}'
      # END
      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml --configuration ./phpunit.xml  --testsuite Ordered
      - name: Checkstyle
        run: php vendor/phpcheckstyle/phpcheckstyle/run.php --src src --config ./php-on-couch-style.xml --format console
      - run: 'bash <(curl -s https://codecov.io/bash)'
